FORMAT: 1A
HOST: https://hostname/ipmx/is-xx

# IS-XX API
This API Blueprint demonstrates a IS-XX extension to AMWA [NMOS API](https://amwa-tv.github.io/nmos).

NOTE: This document is a **work in progress**.

# Group API Root 

## Base [/]

### Retrieve a list of endpoints [GET]

+ Response 200 (application/json)

        [
            "receivers/",
            "senders/"
        ]

# Group Receiver
This section groups requests related Receiver's side

## Receivers collection [/receivers]

### Retrieve a list of receivers with IS-XX support[GET]

+ Response 200 (application/json)

        [
            "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5".
            "dsgd453g-54fx-66xg-23sa-gh57kgd44ag7",
            ...
            "7jkgd03l-35hf-dsf3-v442-fsdaj1Adall1"
        ]

## Single receiver endpoint [/receivers/{receiver_id}]

+ Parameters
    + receiver_id: `dsgd453g-54fx-66xg-23sa-gh57kgd44ag7` (string)

        The ID of the receiver.

### Receiver attributes [GET]
Retrieves an options for the receiver

+ Response 200 (application/json)

        [
            "edid/"
        ]


## EDID [/receivers/{receiver_id}/edid]
EDID file contains information about viewer attached to the receiver.

+ Parameters
    + receiver_id: `dsgd453g-54fx-66xg-23sa-gh57kgd44ag7` (string)
        
        The ID of the receiver

### Get EDID [GET]
Retrieves the EDID file for the receiver with the given ID.

+ Response 200 (application/json)
    + Attributes (EDID File)

# Group Sender
This section groups requests related Senders's side

## Senders endpoint [/senders]

### List of all senders [GET]

+ Response 200 (application/json)

        [
            "9126cc2f-4c26-4c9b-a6cd-93c4381c9be5".
            "dsgd453g-54fx-66xg-23sa-gh57kgd44ag7",
            ...
            "7jkgd03l-35hf-dsf3-v442-fsdaj1Adall1"
        ]

## Single sender endpoint [/senders/{sender_id}]
+ Parameters
    + sender_id: `dsgd453g-54fx-66xg-23sa-gh57kgd44ag7` (string)
        
        The ID of the sender

### Senders attributes [GET]
Retrieves an options for the sender

+ Response 200 (application/json)

        [
            "flow/"
        ]


## Flow [/senders/{sender_id}/flow]
Represents a list of dynamic fields in the flow that can be changed

+ Parameters
    + sender_id: `dsgd453g-54fx-66xg-23sa-gh57kgd44ag7` (string)
        
        The ID of the sender

### Get flow dynamuc params [GET]
Retrives an object with all dynamic flow's fields and their active values

+ Response 200 (application/json)
    + Attributes (Flow Params)

### Update flow dynamuc params [PATCH]
Retrives an object with all dynamic flow's fields and their active values

+ Request (application/json)
    + Attributes (Flow Params)

+ Response 200 (application/json)
    + Attributes (Flow Params)


# Data Structures

## Color (object)
+ x: 256 (number, required)
+ y: 256 (number, required)

## EDID File (object)
+ edid_version: v1.4 (string, required)
+ display_type: RGB (string, required)
+ horizontal_screen_size: 2048 (number, required)
+ vertical_screen_size: 1080 (number, required)
+ gamma: 2.2 (number, required)
+ color_params (object)
    + red (Color)
    + green (Color)
    + blue (Color)
    + white (Color)


## Flow Params (object)
+ frame_width: 1080 (number, required)
+ frame_height: 2048 (number, required)