@startuml EDID_Negotiation_sequence

autonumber
hide footbox
skinparam BoxPadding 30

!pragma teoz true

actor User

box "Receiver Side"
participant "Receiver"
endbox
box "Sender Side"
participant "Sender IS-04"
participant "Sender IS-XX"
participant "HW Source"
endbox


== Getting a Receiver's EDID file == 

User -> "Receiver" : Get Receiver's EDID File

|||
ref over User, Receiver : The same steps as on \n"Get receiver's params" diagram.
|||

"Receiver" -> "User" : Return JSON with EDID representation

|||

User -> User: Understanding monitor's capabilities
note right
{
    ...
    "horizontal_screen_size": 1024,
    "vertical_screen_size": 768
    ...
}
end note

== Looking for a Sender's IS-XX Extension ==

User -> "Sender IS-04" ++ : GET /senders/{id}
return Sender object

User -> User : Find in Sender object\n an ID of the Device
User -> "Sender IS-04" ++ : GET /devices/{id}
return Device object

|||

User -> User : Verify that device's controls\n includes IS-XX

|||

== Sending EDID data to the Sender for negotiation ==

User -> "Sender IS-XX" ++: POST /senderes/{id}/flow/negotiation

"Sender IS-XX" -> "Sender IS-XX": Negotiate received params\n with active params

|||

"Sender IS-XX" -> "HW Source" ++: Change resolution form\n 1920x1080 to 1024x768
return Success message
"Sender IS-XX" -> "Sender IS-XX": Update flow's active params in storage
"Sender IS-XX" --> "Sender IS-04": Update IS-04 flow resource with new values

|||

"Sender IS-XX" --> User: Updated flow's params
deactivate

@enduml