@startuml Get_receiver_params_activity

|Customer|
start
:Looking for 
**IS-XX** extension;

|NMOS Receiver|
if (Supports **IS-XX**?) then (no)
    stop
else (yes)
    :Return **IS-XX** URL;
endif

|Customer|
:Looking for 
monitor's params;

|NMOS Receiver|
:Ask monitor for EDID file;

|Monitor|
if (Has EDID file?) then (no)
    stop
else (yes)
    :Return EDID file;
endif

|NMOS Receiver|
:Parse EDID file;
:Tranform EDID options 
    to **IS-XX** params;
:Return monitor's params;

|Customer|
:Working with monitor's params;
    
stop

@enduml